// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List printing products in the catalog, optionally filtered by category or search text.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Text to match against product name."),
    category: z.string().trim().min(1).optional().describe("Filter by product category."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum products to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }) => {
    let query = supabaseAnon().from("products").select("id,name,category,description,price,stock,image_url").order("name").limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single product by its id, including price, stock and description.",
  inputSchema: { product_id: z2.string().uuid().describe("The product id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_id }) => {
    const { data, error } = await supabaseAnon().from("products").select("id,name,category,description,price,stock,image_url").eq("id", product_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { product: data } };
  }
});

// src/lib/mcp/tools/list-cart.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_cart_default = defineTool3({
  name: "list_cart",
  title: "List cart items",
  description: "List the signed-in user's shopping cart items with product details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("cart_items").select("id,quantity,created_at,products(id,name,price,category)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-to-cart.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var add_to_cart_default = defineTool4({
  name: "add_to_cart",
  title: "Add to cart",
  description: "Add a product to the signed-in user's shopping cart.",
  inputSchema: {
    product_id: z3.string().uuid().describe("The product id to add."),
    quantity: z3.number().int().min(1).max(1e3).optional().describe("Quantity to add (default 1).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ product_id, quantity }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("cart_items").insert({ user_id: userId, product_id, quantity: quantity ?? 1 }).select("id,product_id,quantity");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}) }], structuredContent: { item: data?.[0] } };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var list_orders_default = defineTool5({
  name: "list_orders",
  title: "List orders",
  description: "List the signed-in user's orders with their items and status.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional().describe("Maximum orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("orders").select("id,status,total_amount,shipping_city,created_at,order_items(id,product_id,quantity,price)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "crezdwmedvotisqszmnr";
var mcp_default = defineMcp({
  name: "elka-printing",
  title: "elka-printing",
  version: "0.1.0",
  instructions: "Tools for the Elka Grafika printing shop. Browse the product catalog, and for signed-in users read their cart and orders or add products to the cart.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, list_cart_default, add_to_cart_default, list_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
